# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
City.destroy_all
city = City.create!(name:'Chicago', state: 'IL', country: 'USA', description: 'Steely skycrapers, top chefs, rocking festivals – the Windy City will blow you away with its low-key cultured awesomeness')
city.tourist_attractions.create!(name:'Navy Pier', description:'You can''t truly experience Chicago without a trip to Navy Pier. This 50-acre playground of entertainment, museums, activities, restaurants, and shops is the perfect place for some family fun time.
  First on the list is a trip to Pier Park for a ride on the 150-foot Ferris wheel, which offers great city and Lake Michigan views and is open year-round. Also check out the whimsical musical carousel, Wave Swinger lift-and-twirl ride, miniature golf course, remote control boats, and more.

  Next, grab the kids and go explore educational wonders at the Chicago Children''s Museum. Discover dozens of lively interactive exhibits such as BIG Backyard, Dinosaur Expedition, Inventing Lab, and the Kovler Family Climbing Schooner. Then get lost in Amazing Chicago''s Funhouse Maze where you will be entertained by the Mirror Maze, Spinning Tunnel, and more.

  See a blockbuster on Chicago''s largest movie screen at the IMAX Theater. Or take a dynamic high-speed motion thrill ride to Antarctica, the moon and more on the Transporter FX.

  And during the warmer months, it''s prime time for the Pier''s boating season. Get off the shores and board one of the many sightseeing and dining boat cruises. Take your pick of vessel, all lined up along the waterfront, from Seadog and Shoreline to The Odyssey. The views of Navy Pier and the Chicago skyline can''t be beat.

  Not limited to a specific season, entertainment at Chicago Shakespeare Theater delights year-round. Catch cutting edge performances and classics at this highly-regarded cultural institution, where their tradition of excellence has been recognized with the Regional Theater Tony Award, three Laurence Olivier Awards, and 70 total Joseph Jefferson Awards', category:'landmark, entertainment', latitude: 41.89139, longitude: -87.5997)
city.tourist_attractions.create!(name:'Milennium Park- the "Bean"', description:' The Cloud Gate Sculpture, also known as the "bean," is one of the highlights of Millennium Park. Designed by the artists Anish Kapoor, the Chicago the Bean sculpture is made of 168 highly polished stainless steel plates - giving the appearance of liquid mercury. Up close, the highly reflective nature of the sculpture captures the beautiful skyline of Chicago. The Cloud Gate Sculpture has thus become a tourist hot spot and is the perfect place to take your vacation snapshots.', category:'landmark', latitude: 41.8827, longitude: -87.6233)
city.tourist_attractions.create!(name:'SkyDeck-Willis tower', description:'SkyDeck Chicago is the Observatory Deck of the world-famous Willis Tower (formerly the Sears Tower). Perched 1,353 feet up in the air on the 103rd floor of the tower, SkyDeck Chicago provides some of the best views of the city, from Navy Pier to Soldier Field. You’ll also find interactive exhibits and historical photographs to learn about the building’s prestigious history. It’s a must-see Chicago attraction and a perennial favorite with visitors from around the globe.', category:'landmark, skyline', latitude: 41.8789, longitude: -87.6358)
city.tourist_attractions.create!(name:'360 Chicago', description:'Formerly known as the John Hancock Observatory, 360 Chicago offers dining, sights and an interactive tour far above the city streets. From 1,000 feet up on the 94th floor, you can see up to 55 miles out and four states—you''ll feel as if you''re along for the ride as you watch airplanes whiz by. A recent addition is the Tilt attraction, which allows visitors to step onto an enclosed platform that extends from the building at a 30 degree angle.', category:'landmark, skyline', latitude: 41.898947, longitude: -87.622916)
city.tourist_attractions.create!(name:'Field museum of natural history', description:'The Field Museum of Natural History, located in Chicago, Illinois, USA, is one of the largest natural history museums in the world.[2] The museum maintains its status as a premier natural history museum through the size and quality of its educational and scientific programs,[3][4] as well as due to its extensive scientific specimen and artifact collections.[5] The diverse, high quality permanent exhibitions,[6] which attract up to 2 million visitors annually, range from the earliest fossils to past and current cultures from around the world to interactive programming demonstrating today’s urgent conservation needs.', category:'museum', latitude: 41.866261, longitude: -87.6169805)



# city = City.create!(name:'New York', state: 'NY', country: 'USA', description: 'Steely skycrapers, top chefs, rocking festivals – the Windy City will blow you away with its low-key cultured awesomeness')
User.create(name:"Max", email:"maxb@ga.com",password:"blahblah")
